version: '3'

services:
  apache:
    build: .docker/apache
    container_name: sf4_apache
    ports:
      - 8080:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/sf4
    depends_on:
      - php

  mysql:
    image: mysql:8
    container_name: sf4_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mybeers
      MYSQL_USER: mybeers
      MYSQL_PASSWORD: mybeers

  php:
    build: .docker/php
    container_name: sf4_php
    volumes:
      - .:/home/wwwroot/sf4
    depends_on:
      - mysql
